// Comprehensive list of Accra areas and neighborhoods (expanded)
export const accraAreas = [
  // High-end Residential Areas
  "East Legon",
  "West Legon",
  "Airport Residential",
  "Cantonments",
  "Roman Ridge",
  "Labone",
  "Osu",
  "Dansoman",
  "Tesano",
  "Achimota",
  "Abelemkpe",
  "Dzorwulu",
  "Kokomlemle",
  "North Legon",
  "North Ridge",
  "South Ridge",
  "North Kaneshie",
  "South Odorkor",
  "Taifa",
  "Awoshie",

  // Middle-income Areas
  "Adenta",
  "Madina",
  "Haasto",
  "Atomic",
  "Agbogba",
  "Oyarifa",
  "Pantang",
  "Ashaley Botwe",
  "Ashalaja",
  "Amanfrom",
  "West Adenta",
  "Weija",
  "Gbawe",
  "Mallam",
  "Kasoa",
  "Dome",
  "Kwabenya",
  "Haatso",
  "Santa Maria",
  "Lapaz",
  "Apenkwa",
  "Darkuman",
  "Kaneshie",
  "Odorkor",
  "New Gbawe",
  "Tabora",
  "Israel",
  "Ablekuma",
  "North Odorkor",

  // Business & Commercial Districts
  "Airport City",
  "Ridge",
  "North Industrial Area",
  "South Industrial Area",
  "Central Business District",
  "Makola",
  "Kaneshie Market",
  "Circle",
  "Kwame Nkrumah Interchange",
  "Tudu",
  "Abossey Okai",
  "Agbogbloshie",

  // University & Educational Areas
  "University of Ghana",
  "Legon",
  "Accra Technical University",
  "KNUST Accra Campus",
  "GIMPA",
  "Ashesi University",
  "Central University",
  "Wisconsin University College",
  "Valley View University",
  "UPS (University of Professional Studies)",

  // Coastal & Beach Areas
  "Labadi",
  "Teshie",
  "Nungua",
  "Tema Community 1",
  "Tema Community 2",
  "Tema Community 3",
  "Tema Community 4",
  "Tema Community 5",
  "Tema Community 6",
  "Tema Community 7",
  "Tema Community 8",
  "Tema Community 9",
  "Tema Community 10",
  "Sakumono",
  "Coco Beach",
  "Korle Gonno",
  "Chorkor",
  "Mamprobi",
  "James Town",
  "La Palm",

  // Traditional & Historical Areas
  "Usher Town",
  "Christiansborg",
  "Osu Castle",
  "Independence Square",
  "Korle Bu",
  "Salaga",
  "Adabraka",

  // New Development & Emerging Areas
  "Spintex Road",
  "Tema Motorway",
  "Baatsona",
  "Klagon",
  "Lashibi",
  "Community 18",
  "Community 20",
  "Community 25",
  "McCarthy Hill",
  "Bortianor",
  "Dawhenya",
  "Afienya",
  "Prampram",
  "Amrahia",
  "Oyibi",
  "Santeo",
  "East Airport",
  "Opeibea",
  "Bubuashie",
  "Shiashie",
  "Adjiringanor",
  "Abelemkpe Extension",
  "Adjiringanor Extension",
  "East Adenta",
  "Pokuase Hills",

  // Suburban & Outskirts Areas
  "Amasaman",
  "Ofankor",
  "Pokuase",
  "Dodowa",
  "Adjen Kotoku",
  "Nsawam",
  "Ayi Mensah",
  "Oyarifa Hills",
  "Peduase",
  "Oyibi Hills",
  "Teiman",
  "Sowutuom",
  "Ablekuma Fanmilk",
  "Ablekuma Joma",
  "Awoshie Onyinase",
  "Fise",
  "Ashaley Botwe School Junction",
];
